#Application Configuration
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Agusilveira/spring-boot-API-rest.git
          searchPath: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t
